### Create course
POST localhost:8080/course/create
Content-Type: application/json

{
  "name": "Valibek",
  "price": 90.45,
  "duration": "2 month"
}


### Get all course
GET localhost:8080/course/all

### Get by id
GET localhost:8080/course/4


### Update by id
PUT localhost:8080/course/4
Content-Type: application/json

{
  "name": "Abdullo",
  "price": 12.24
}

### Delete by id
DELETE localhost:8080/course/4

### Get by name
GET localhost:8080/course/name?name=Ali

### Get by prices
GET localhost:8080/course/prices?priceI=10.0&priceF=12.25

### GEt by dates
GET localhost:8080/course/dates?dateI=2023-07-03&dateF=2023-07-04

### Get by pages
GET localhost:8080/course/pagination?page=1&size=2


### Filter
POST localhost:8080/course/filter
Content-Type: application/json

{
  "duration": "12 Month"
}
