### Create course
POST localhost:8080/course/create
Content-Type: application/json

{
  "name": "Vali",
  "price": 90.8,
  "duration": "1 month"
}


### Get all course
GET localhost:8080/course/all

### Get by id
GET localhost:8080/course/1


### Update by id
PUT localhost:8080/course/1
Content-Type: application/json

{
  "name": "Abdullo",
  "price": 12.24
}

### Delete by id
DELETE localhost:8080/course/7

### Get by name
GET localhost:8080/course/name?name=Ali

### Get by prices
GET localhost:8080/course/prices?priceI=10.0&priceF=12.25

### GEt by dates
GET localhost:8080/course/dates?dateI=2023-07-03&dateF=2023-07-04
